[package]
name="tap_core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Core Timeline Aggregation Protocol library: a fast, efficient and trustless unidirectional micro-payments system."
