[package]
name="tap_aggregator"
version = "0.1.0"
edition.workspace = true
license.workspace = true
readme = "README.md"
description = "A JSON-RPC service for the Timeline Aggregation Protocol that lets clients request an aggregate receipt from a list of individual receipts."

[[bin]]
name = "tap_aggregator"
path = "src/main.rs"

[dependencies]
tap_core = { path = "../tap_core" }
