[package]
name = "tap_integration_tests"
version = "0.1.1"
edition.workspace = true
license.workspace = true
autotests = false
description = "Integration tests for the Time Aggregation Protocol."
publish = false

[dependencies]
tap_aggregator = { path = "../tap_aggregator" }
tap_core = { path = "../tap_core" }

[[test]]
name = "test"
path = "tests/lib.rs"
