name: Publish crates

# Runs when the workflow "tests" is completed
on:
    workflow_run:
        workflows: ["tests"]
        branches: [main]
        types:
            - completed

jobs:
    publish:
        runs-on: ubuntu-latest
        # Run only if the workflow "tests" was successful
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v2
            - name: Install cargo-workspaces
              run: cargo install cargo-workspaces
            - name: Publish workspace crates
              run: cargo workspaces publish --from-git -y
              env:
                  CARGO_AUTH_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
