on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_publish:
        type: boolean
        description: >-
          Force publish-crates. Note that if the current crate version is already 
          published, it will do nothing.
        required: false
        default: false

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - name: Release please
        id: release-please
        uses: google-github-actions/release-please-action@8016a6649226f2ec88ed05441c11bb5410a22d29 #v3.7.10
        with:
          command: manifest

  publish-crates:
    runs-on: ubuntu-latest
    # run only if release-please had released a new version
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true' || github.event.inputs.force_publish == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces
      - name: Publish workspace crates
        # `--no-remove-dev-deps` is a workaround for https://github.com/pksunkara/cargo-workspaces/issues/103
        run: cargo workspaces publish --from-git --no-remove-dev-deps -y
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
