on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@8016a6649226f2ec88ed05441c11bb5410a22d29 #v3.7.10
        id: release-please
        with:
          command: manifest

  publish-crates:
    runs-on: ubuntu-latest
    # run only if release-please had released a new version
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces
      - name: Publish workspace crates
        run: cargo workspaces publish --from-git -y
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
